version: 1
disable_existing_loggers: false
formatters:
  simple:
    # format: '\x1b[33;20m %(levelname)s: %(message)s (in %(name)s)\x1b[0m'
    # format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s (%(filename)s:%(lineno)d)'
    format: '[%(levelname)s][%(filename)s:%(lineno)d] %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
#loggers:
#  werkzeug:
#    level: ERROR
#    handlers: [ console ]
#    propagate: no
root:
  level: INFO
  handlers: [console]
