version: 2

updates:
  # This will check for updates to github actions every day
  # https://docs.github.com/en/enterprise-server@3.4/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "development"
    schedule:
      interval: "weekly"
    assignees:
      - "eddiebergman"
    reviewers:
      - "eddiebergman"
    commit-message:
      include: "chore: "
