#!/usr/bin/env python

import logging
import sys
import os
import inspect
cmd_folder = os.path.realpath(os.path.abspath(os.path.split(inspect.getfile( inspect.currentframe() ))[0]))
cmd_folder = os.path.realpath(os.path.join(cmd_folder, ".."))
if cmd_folder not in sys.path:
    sys.path.append(cmd_folder)

from smac.smac_cli import SMAC


if __name__ == "__main__":
    
    logging.basicConfig(level=logging.INFO)
    
    smac = SMAC()
    smac.main_cli()
    
