name: pre-commit

on:
  # Manually triggerable in GitHub
  workflow_dispatch:

  # When a push occurs on either of these branches
  push:
    branches:
      - main
      - development

  # When a push occurs on a PR that targets these branches
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main
      - development

jobs:
  run-all-files:
    if : ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install pre-commit
      run: |
        pip install pre-commit
        pre-commit install

    - name: Run pre-commit
      run: |
        pre-commit run --all-files
